
server.port=8080

jwt.secret=checkautos-super-secret-key-2024-must-be-at-least-256bits-long!!
jwt.expiration.ms=86400000


logging.level.com.checkautos=DEBUG
logging.level.org.springframework.security=WARN


spring.data.mongodb.uri=mongodb://localhost:27017/checkautos
spring.data.mongodb.database=checkautos